version: "3"

services:
  app:
    build: .
    command: yarn migrations
    command: yarn dev
    ports:
      - "5001:5001"
    links:
      - postgres
    volumes:
      - ".:/usr/app"

  postgres:
    image: postgres:12.4
    container_name: nlw
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST= db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
